[project]
name = "jarbinlocalapi"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "jarbin-toolkit-config==0.1.2.3",
    "jarbin-toolkit-error==0.1.6.2",
    "jarbin-toolkit-jartest==0.1.5.1",
    "jarbin-toolkit-log==0.2.3.1",
    "httpx==0.28.1",
    "jarbin-toolkit-action==0.1.2.3",
    "pip==26.2.1",
    "uvicorn[standard]==0.52.4",
]
